language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.9
services:
  - mysql # start MySQL on startup
before_script:
  - "mysql -uroot -e \"DELETE from mysql.db WHERE Db = 'test\\_%';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test_allowed DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test_allowed.* TO 'test_user'@'localhost' IDENTIFIED BY '1234';\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test_denied DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"select * from mysql.db;\""
  - "mysql -uroot -e \"select * from mysql.user;\""
