language: node_js
node_js:
  - "0.12" # legacy release
  - "4"    # latest stable release
  - "5"    # latest development release

# This version of node/NAN/v8 requires a C++11 compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

# This causes `Job is already running: mysql`
#services:
#  - mysql # start MySQL on startup

before_script:
  - "mysql -uroot -e \"DELETE FROM mysql.db WHERE Db = 'test\\_%';\""
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE Host = 'localhost' AND User = '';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test_allowed DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test_allowed.* TO 'test_user'@'localhost' IDENTIFIED BY '1234';\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test_denied DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  # Some extras for Travis-CI only
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE User = 'travis';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - node --version
  - npm --version
